apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
spec:
  selector:
    app: portfolio
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 3000
      nodePort: 30080        
  type: NodePort
